language: node_js
node_js:
- '8'
- '7'
- '6'
- '5'
- '4'
os:
- linux
- osx
dist: trusty
osx_image: xcode7.3
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    export CXX=g++-6 CC=gcc-6
  fi
install:
- npm install cmake-js -g
- npm install
script:
- npm test
- npm run unittest
after_success:
- |
  if [ "$TRAVIS_BRANCH" == "pre-gyp-integration" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    ./node_modules/.bin/node-pre-gyp package
    ./node_modules/.bin/node-pre-gyp-github publish
  fi
env:
  global:
  - secure: awtc8YbvzymwOkEeMK61m6L8bFZPnRP6Dz0AXhEoomKx69mmt6+cIm3HAV7birYcsv581ygekdhVseZvRepdQeB0yCb3fUcdeNFfM7/2UYCbDV1kRjAIxcbWbinADgFaBQs2xnTsrdoxV8ftLgpv+7XzGcPCvffXHWso5xSZardot2t12qV4m6Yb1iZOh+zStV8Jx3Vnc5wbG5IcT1kHTWI5V2CjuQANK6OmYfz2d05kAUqSdjrdr2JlNNwaxMTAc2oJYOPEKa3a0xAxIXByPsEtjoTqvy6Vqtyp7go1DuXIpeSwf10iNvmxdtIS3Fu8ReO19fTRp+jW21PcDwl+PRNtTo/oPQdM7uuVUtJiTxu1GcJKvD3rdXMrld8C5SD4Vhcy1M8IeUt9eruM354fkaXYM55rriSydm8y1zceKQuBEHVdpEWOgBHcrlT6fuW1pqqKFVjTB5+AIYdQoWqI3D04yiFvXyn32e/Vsyvd6hp4ItPt2DWtFWBKiKDpqkTbeZiVuHNqnHMALuwxH8zTPlfRVaDeds3U1KuplPiRjfdE8IYndos28EXzrg+qkpCUBSplBkPO4KmvuSV4sy5/yigdUrn87kc63clj974sHdFLeE+OFr6sD4fXic/YiI70MEC5f8ACvGt/MgXRBBijPC80BvSVvUNHpAnTVX6zbGQ=
