language: node_js
node_js:
- '8'
- '7'
- '6'
- '5'
- '4'
os:
- linux
- osx
dist: trusty
osx_image: xcode7.3
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    export CXX=g++-6 CC=gcc-6
  fi
install:
- npm install cmake-js -g
- npm install
script:
- npm test
- npm run unittest
after_success:
- |
  if [ "$TRAVIS_BRANCH" == "pre-gyp-integration" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    ./node_modules/.bin/node-pre-gyp package
    ./node_modules/.bin/node-pre-gyp-github publish
  fi
env:
  global:
  - secure: fQHeDDgUqmaiexDJjh+plCWyoBMhl10PEdjAlI4vTdPmJsZW0g4Zx3r7te/+azJMQ0d397l4XkmSpwvmnJ6y3AQAB/h5dwbZ30FXXmCE+Kw7RPjP5ElYRAGjxCKtVTrDyE73voAZPCDCWCeGPEUx2Bzw1p8d286LaEj5lXXjEf0SCs+7eerz/8m5a9RwauP6RC4hlgK73Mw/j+2IOfZi29u5HnuYvf8OZPF4b553PRz+27EdCXKadjtcr0mr3+mAQRrwF6K6hxdxXkByfOGGTlUoA9w9T469TmW4qPLXVhOsj5vYwKQJfkesjgNqB0ROXxrOGw+fEN8oEAyxn51p7rMoW7APWovyhyjYQxTZec3itEtVEnkeB8Qlq/a14gcwB1A0upBDeFpvPO4tdY81QnGbEXHyJEdzERr+zkpwcEmRRo6Le7aNYAtdJKXkBrJeXKPwm4FTdn/e2ODEVx39DzcEHZrQGt0JJvr3UcS7yLXBzB20igHI/WNv495mWpyKsgrs7wAEJwhpMsEEa+T1c9VjoRFsCrgz0AVDbs6IuO7z0WOa08TcbRH5ksLEGjbUmILmYN0oVmKWcKUiJ6k9nIwZ21sTqR4NGcfL7n9Bv5Nm29znBLRp+da1ygZwOZn3rxSzbH+Md9H6PQQacSMjvuTa5GDRw0ClyEKKago2QqI=
