language: node_js
node_js:
- '8'
- '6'
- '4.5.0'
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

matrix:
  include:
  - os: linux
    compiler: g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER_OVERRIDE="CXX=g++-6 CC=gcc-6"

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    if [ "$COMPILER_OVERRIDE" == "" ]; then
      #use g++5 by default
      export CXX="g++-5" CC="gcc-5"
    else
      export ${COMPILER_OVERRIDE}
    fi
  fi
install:
- npm install cmake-js -g
- npm install
script:
- npm test
- npm run unittest
after_success:
- |
  if [ "$TRAVIS_BRANCH" == "pre-gyp-integration" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID
    echo TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    echo TRAVIS_JOB_ID=$TRAVIS_JOB_ID
    echo TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER
    echo TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
    echo TRAVIS_TAG=$TRAVIS_TAG
    ./node_modules/.bin/node-pre-gyp package
    ./node_modules/.bin/node-pre-gyp-github publish
  fi
env:
  global:
    secure: S7DDixQ9tPK0hi7iGGNhipNUZtOa3qN4xwKpvUdB8XSBMP7N2LBjh/Bzjh/9zq7dyAVbUBrXHZkGICIYEDpGvjenIGUcr0mUQc6TDcf8Pk0OgY1jpF3I/eBdKX8e+WnfmOwD87SABQGdivlkZw6LXgT1Cw3fSxGZnkBHmjpKtJASZNi3AbS8agtiDPBwSxWiQQvIXdp35fIKh08KTeWbyZ9f9tlmVXZlbN78EXANR3Jc1UcL2JgCJoj7XxESpyUQpZP+rOrBPd9vhUORsK/et5ZTKJb66oeJcK4fq21hqMJxDIhpNnBgFC6KEmgOyDeqjLCp5a+520+QmE0+V0EAgVDXSaaLBgkV3DJShhuTX+ti4NgAc1MAxbDkXBF6WUAT3bOvr0BpuUhYW8j+wAs5bv1YnPYXja2umK+shVQ3epXtZ/Cdg3rhNymb3W6q36+z3pbB/ceRsOmLJollbF/18Iumo/iYHfxYiVXrF5OdVMexk/dLQ3s6FyjIqjxERjQhZqX34PTNmZBYk/NTyLut27fxEp21uhHqH6L7Un0IiDBTpsnpVhwRyOrzqFi/CJJC/Lbw76M1j47LPEymTz3E8rReDVBfj7Wfce8pB0D41moR/AbgtZUPeNH9XAduHz0ScMJNv+i0kH4SmqEvSbSVu3liknYlRumFn7MAEk2vfps=
