language: node_js
node_js:
- '8'
- '7'
- '6'
- '5'
- '4'
os:
- linux
- osx
dist: trusty
osx_image: xcode7.3
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    export CXX=g++-6 CC=gcc-6
  fi
install:
- npm install cmake-js -g
- npm install
script:
- npm test
- npm run unittest
after_success:
- |
  if [ "$TRAVIS_BRANCH" == "pre-gyp-integration" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    ./node_modules/.bin/node-pre-gyp package
    ./node_modules/.bin/node-pre-gyp-github publish
  fi
env:
  global:
  # NODE_PRE_GYP_GITHUB_TOKEN
  - secure: OxHEhBMHAXIsEdMu1IZrqwzrzW9v7Ib9sK/2mz2pynQOtPeRyZ4Z/hZ9RuCprP7NlitRH+n+k7giC6BZyqaj0JQwywEZavLOmoe3DThIJPvXzfzqFiQulguajsK/59dQGakuJy+AYg+6bf4Ami2Krt96D42b9UHnJ6YyrrmEaOreqA9QZavw55SFqAyC4vSZEemgeDMFdwkaKz+PH5Rv5o2oGnrZ7JVOchC/0eLcAKAbJQlWdgULb6+2px2032z2OSyfc2dyM20+uhyqJCTu12DNRB2FFnY7IvZU1FZTljU8jBDtth7EgEAKCCp9Y6KmnIDGpPod0GdFL6esaH48AHXqjIof2dQP9T0XPU1Xq8XdilgdEQMVGOjSI5AvylGhQZ9D/9jkijI3SViK58brPXUoyl3gDNj4pSHbLtJ35J5DEkBV97xGOQq5m0KZlrRsUw5dpGzXy3ADgrxH27Am7paoaJ+pxFWY5VfAt2eVjALTHoknbYhylDy95BOybQBUQ+1/njfVPCj96WWK4LE84PTazkJmO5w7CZ1F+UbFE/7AgGDyizlg0hNcO6KuZdUy7ayXCuw08d9wof2XHnJSGNRfbAuUa2gAIwrxepldcSOehKJ6c2aJg+5ucdnmMzfgeO64xkCC28FyW8Z8cI+bgjYGJRfvQK8DZmQeC0kXKsY=
