image:
- Visual Studio 2017

environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: E7tOEoLBk/oqyFjOWj0E6bKFEubCQDekejvK7YHgefObKnV2inw/eLI+zK88DdiV

  matrix:
    - nodejs_version: 4
    - nodejs_version: 5
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8

platform:
- x64

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install cmake-js -g
- npm install

# Skip MSBuild stage
build: off

test_script:
- npm test
- npm run unittest

deploy_script:
# Run deploy scripts only when new commit pushed in branch pre-gyp-integration 
- |
  IF "%APPVEYOR_REPO_BRANCH%" == "pre-gyp-integration" (
    IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" (
      IF "%APPVEYOR_REPO_TAG%" == "false" (
        .\node_modules\.bin\node-pre-gyp package
        .\node_modules\.bin\node-pre-gyp-github publish
      )
    )
  )
